# Information about the dist-git repo
repo:
  type: rpms   # default is "rpms", but can be set to "apbs" for new dist-git repo type

# The image name this repo builds. This is the value set into LABEL:name (used by OSBS when naming image).
name: openshift3/node

from:
  # The FROM field in the Dockerfile will be updated with the name configured for the repo.
  # The image label will be updated with the last version built.
  member: openshift-enterprise-docker   # From a member of the group
  # distgit: some_nongroup_distgit      # Must be cloned and last version/release extracted
  # image: namespace/imagename:tag # a literal image name to use
  # stream: rhel    # an image stream to use

# Owners are emailed when merge process detects a substantitive change in source Dockerfile. Owners
# get one email with the "merged" result after a source change. Owners are also emailed when an image
# is no longer building.
owners: []

# Labels that will be set into the Dockerfile. name, version, and release will be set automatically.
# com.redhat.component  will default to the dist-git repo name (openshift-enterprise-node-docker).
labels:
  vendor: Red Hat
  License: GPLv2+
  architecture: "x86_64"
  io.k8s.display-name: "OpenShift Container Platform Node"
  io.k8s.description: "This is a component of OpenShift Container Platform and contains the software for individual nodes when using SDN."
  io.openshift.tags: "openshift,node"

enabled_repos:
    - rhel-server-ose-rpms
    - rhel-fast-datapath-rpms
    - rhel-server-extras-rpms

content:
  source:
    # If the source has an alias defined, an extracted local directory can be specified on the local file system
    # using --source alias path.
    alias: ose
    path: images/node

    # Non-default modifications to perform on the git Dockerfile. Default steps include updating "FROM".
    # The Origin RPM "origin-sdn-ovs" has a different name when packaged for OCP.
    modifications:
      - action: replace
        match: "origin-sdn-ovs"
        replacement: "atomic-openshift-sdn-ovs"
