# The image name this repo builds. This is the value set into LABEL:name (used by OSBS when naming image).
name: openshift3/ose-base

from:
  stream: rhel

labels:
  vendor: Red Hat
  License: GPLv2+
  architecture: "x86_64"
  io.k8s.display-name: "OpenShift Container Platform RHEL 7 Base"
  io.k8s.description: "This is the base image from which all OpenShift Container Platform images inherit."
  io.openshift.tags: "openshift,base"

content:
  source:
    alias: ose
    path: images/base
    modifications:
      # addition of centos ceph package incompatible with RHEL builds
      # added here: https://github.com/openshift/ose/commit/2120bad7fb4e1682c7f73107d577d8368b68cd41#diff-065f169938b73c43248f266b4fc6291bR10
      # follow up with storage team required. Brute force removing for now
      - action: replace
        match: "yum install -y centos-release-ceph-luminous && "
        replacement: ""
      - action: replace
        match: "rpm -V centos-release-ceph-luminous && "
        replacement: ""
