from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Application metrics collector.
  io.k8s.display-name: Hawkular OpenShift Agent
  io.openshift.tags: metrics,hawkular,hawkular-openshift-agent
  vendor: Red Hat
name: openshift3/metrics-hawkular-openshift-agent
owners:
- hawkular-dev@lists.jboss.org
repo:
  type: rpms
no_oit_comments: true
enabled_repos:
    - rhel-server-ose-rpms
