content:
  source:
    alias: ose
    path: images/dockerregistry
    dockerfile: Dockerfile.product
from:
  member: openshift-enterprise-base-docker
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is a component ofOpenShift Container Platform and exposes
    a Docker registry that is integrated with the cluster for authentication and management.
  io.k8s.display-name: OpenShift Container Platform Image Registry
  io.openshift.tags: openshift,docker,registry
  vendor: Red Hat
name: openshift3/ose-docker-registry
owners: []
repo:
  type: rpms
