content:
  source:
    alias: jenkins
    path: '1'
from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Jenkins is a continuous integration server
  io.k8s.display-name: Jenkins 1.651.2
  io.openshift.tags: jenkins,jenkins1,ci
  vendor: Red Hat
name: openshift3/jenkins-1-rhel7
owners:
- bparees@redhat.com
repo:
  type: rpms
