content:
  source:
    alias: ose
    path: images/pod
    dockerfile: Dockerfile.product
from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is a component of OpenShift Container Platform and holds
    on to the shared Linux namespaces within a Pod.
  io.k8s.display-name: OpenShift Container Platform Pod Infrastructure
  io.openshift.tags: openshift,pod
  vendor: Red Hat
name: openshift3/ose-pod
alt_name: rhel7/pod-infrastructure
owners: []
repo:
  type: rpms

enabled_repos:
    - rhel-server-ose-rpms