# from missing as logging team will manage direct in distgit

labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Fluentd container for collecting of docker container logs
  io.k8s.display-name: Fluentd
  io.openshift.tags: logging,elk,fluentd
  vendor: Red Hat
name: openshift3/logging-fluentd
owners:
- dev@lists.openshift.redhat.com
repo:
  type: rpms
