content:
  source:
    alias: ose
    path: images/node
from:
  member: openshift-enterprise-docker
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is a component of OpenShift Container Platform and contains
    the software for individual nodes when using SDN.
  io.k8s.display-name: OpenShift Container Platform Node
  io.openshift.tags: openshift,node
  vendor: Red Hat
name: openshift3/node
owners:
- dgoodwin@redhat.com
repo:
  type: rpms
