from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Logging auth proxy
  io.k8s.display-name: Logging auth proxy
  vendor: Red Hat
name: openshift3/logging-auth-proxy
owners:
- dev@lists.openshift.redhat.com
repo:
  type: rpms
