content:
  source:
    alias: ose
    path: images/origin
    modifications:
      - action: replace
        match: "INSTALL_PKGS=\"origin\""
        replacement: "INSTALL_PKGS=\"atomic-openshift\""
from:
  member: openshift-enterprise-base-docker
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: OpenShift Container Platform is a platform for developing, building,
    and deploying containerized applications.
  io.k8s.display-name: OpenShift Container Platform Application Platform
  io.openshift.tags: openshift,core
  vendor: Red Hat
name: openshift3/ose
owners: []
repo:
  type: rpms

enabled_repos:
    - rhel-server-ose-rpms
