from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Fluentd container for collecting of docker container logs
  io.k8s.display-name: Fluentd 0.12.39
  io.openshift.tags: logging,elk,fluentd
  vendor: Red Hat
name: openshift3/logging-fluentd
owners:
- dev@lists.openshift.redhat.com
repo:
  type: rpms
no_oit_comments: true
enabled_repos:
    - rhel-server-ose-rpms
