content:
  source:
    alias: openshift-ansible
    path: images/installer
    dockerfile: Dockerfile.rhel7
from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: A containerized openshift-ansible image to let you run playbooks
    to install, upgrade, maintain and check an OpenShift cluster
  io.k8s.display-name: openshift-ansible
  io.openshift.tags: openshift,install,upgrade,ansible
  vendor: Red Hat
name: openshift3/ose-ansible
owners: []
repo:
  type: rpms
enabled_repos:
  - rhel-server-rh-common-rpms
