content:
  source:
    alias: jenkins
    path: slave-maven
    dockerfile: Dockerfile.rhel7
from:
  member: jenkins-slave-base-rhel7-docker
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: The jenkins slave maven image has the maven tools on top of
    the jenkins slave base image.
  io.k8s.display-name: Jenkins Slave Maven
  io.openshift.tags: openshift,jenkins,slave,maven
  vendor: Red Hat
name: "openshift3/jenkins-slave-maven-rhel7"
owners:
- bparees@redhat.com
repo:
  type: rpms
enabled_repos:
    - rhel-server-rhscl-7-rpms
