repo:
  type: rpms
  branch: *OCP_DIST_GIT_BRANCH

name: openshift3/ose

from: 
  # The from field can be set to a stream configured in /streams.yml
  stream: rhel-ocp-3.7

owners: 
  - email@redhat.com
  - email2@redhat.com

labels:
  vendor: Red Hat
  License: GPLv2+
  architecture: x86_64

content:
  method: git
  source: *OCP_GIT_REPO
  filename: images/origin/Dockerfile
