from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Elasticsearch container for EFK aggregated logging storage
  io.k8s.display-name: Elasticsearch 2.4.4
  io.openshift.tags: logging,elk,elasticsearch
  vendor: Red Hat
name: openshift3/logging-elasticsearch
owners:
- dev@lists.openshift.redhat.com
repo:
  type: rpms
no_oit_comments: true
enabled_repos:
    - rhel-server-ose-rpms
    - rhel-server-extra-rpms
