from:
  member: openshift-enterprise-apb-base-docker
labels:
  License: GPLv2+
  vendor: Red Hat
name: openshift3/postgresql-apb
no_oit_comments: true
owners:
- dzager@redhat.com
repo:
  type: apbs
enabled_repos:
    - rhel-server-ose-rpms
