language: python
python:
- '2.7'
deploy:
  matrix:
  - provider: pypi
    skip_cleanup: true
    user: OpenShiftART
    password:
      secure: DoV4ja22s7aKrzc79F/Rs/Y6D76apEyGyK/fO+zETXtvtaxou5OgCFnyBSWOWPUVGmP1mDJra07jhpjWq695c1H8bGxLQ77U4G5d4Q91SfOFQceTsTWb6IFTxcKgmWb+jeOIoZbxPQUinhG1D2U9RK9CLLunJ/H6oHF4mpRqIhHyug5gNxMk/+mS4XGEqWpB5R/h3os6pt+gSLyHFfK3AuuKNHPAu58SIYIeywXkYnWYHZ+mI8wp/pMmM/Ta0EEizgjdWUjHJ3B0RgYnyLYsLD8xAcEYesGrwSzG4W8SjknEwA5yn5eAwbgSK5HkqroywfMCwpnfi+gnJV5tlgMHZxLQsadoNqr9y605+luj+Xl4ahYop1++wuoXdg+3wnmMqL6MFJZ9hkE1IzMjsCdPqTI0XUUxFQK1hkBMu8CTP4xcDC++ScVoC0dp219upzxVF+2FMIhe2dUuTR5twuYD98nBHeeTxS7U3SE+dF1J6Dydsp3X3TjchSkJHladOMC57etshus3riiQx+a1mLCyyVyC+pDGWl7radVokOJEK7xqJM3OpQkkn6HxkOmMZB+0Jjoa2SAp85kFlCL0AOaLOyTT3OtLLtfO7dvEksMimmeSFrKWt8IrQZ6lJ9cspEFoXvqet1oK0Q294FTnsq/ZWYcnFFt0Usu7tTjPTzCx1CM=
    on:
      python: 2.7
      tags: true

script:
- python setup.py install
