language: python
python:
- '2.7'
install:
- echo "Disabling requirements.txt install. Will not work on Travis."
script:
- echo "We should run tests here"
deploy:
  provider: script
  script: pypi_push.sh $PYPI_PASS
  skip_cleanup: true
  skip_existing: true
  on:
    repo: openshift/doozer
    python: 2.7
    tags: true
