from:
  stream: rhel
labels:
  License: GPLv2+
  vendor: Red Hat
name: openshift3/mediawiki-123
no_oit_comments: true
owners:
- dzager@redhat.com
repo:
  type: rpms
enabled_repos:
    - rhel-server-ose-rpms
