from:
  stream: rhel
labels:
  License: GPLv2+
  vendor: Red Hat
no_oit_comments: true
name: openshift3/apb-base
owners:
- dzager@redhat.com
repo:
  type: rpms
enabled_repos:
    - rhel-server-ose-rpms
    - apb-rhel-server-extras-rpms
    - rhel-server-optional-rpms
