content:
  source:
    alias: openshift-ansible
    dockerfile: Dockerfile
from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Ansible code and playbooks for installing Openshift Container
    Platform.
  io.k8s.display-name: Openshift Installer
  io.openshift.tags: openshift,installer
  vendor: Red Hat
name: openshift3/ose-ansible
owners:
- tdawson@redhat.com
repo:
  type: rpms
enabled_repos:
  - rhel-server-rh-common-rpms
