from:
  image: jboss-base-7/jdk8:1.3-11
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Hawkular-Metrics Cassandra image for metrics collection.
  io.k8s.display-name: Cassandra
  io.openshift.tags: metrics,cassandra
  vendor: Red Hat
name: openshift3/metrics-cassandra
owners: []
repo:
  type: rpms
