from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: OpenShift logging event router
  io.k8s.display-name: Logging Event Router
  io.openshift.tags: logging
  vendor: Red Hat
name: openshift3/logging-eventrouter
repo:
  type: rpms
no_oit_comments: true
enabled_repos:
    - rhel-server-ose-rpms
    - rhel-server-extras-rpms
