content:
  source:
    alias: ose
    path: images/egress/router
from:
  member: openshift-enterprise-base-docker
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is a component of OpenShift Origin and contains an egress
    router.
  io.k8s.display-name: OpenShift Origin Egress Router
  io.openshift.tags: openshift,router,egress
  vendor: Red Hat
name: openshift3/ose-egress-router
owners: []
repo:
  type: rpms
