from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: The registry-console image provides a web console for the OpenShift
    Container Platform stand-alone registry.
  io.k8s.display-name: OpenShift Stand-Alone Registry Console
  io.openshift.tags: openshift,docker,registry,console
  vendor: Red Hat
name: openshift3/registry-console
owners:
- dperpeet@redhat.com
repo:
  type: rpms
