# Information about the dist-git repo
repo:
  type: rpms   # default is "rpms", but can be set to "apbs" for new dist-git repo type

# The image name this repo builds. This is the value set into LABEL:name (used by OSBS when naming image).
name: openshift3/node

from:
  # The FROM field in the Dockerfile will be updated with the name configured for the repo.
  # The image label will be updated with the last version built.
  repo: openshift-enterprise-docker

# Owners are emailed when merge process detects a substantitive change in source Dockerfile. Owners
# get one email with the "merged" result after a source change. Owners are also emailed when an image
# is no longer building.
owners:
  - email@redhat.com
  - email2@redhat.com

# Labels that will be set into the Dockerfile. name, version, and release will be set automatically.
# com.redhat.component  will default to the dist-git repo name (openshift-enterprise-node-docker).
labels:
  vendor: Red Hat
  License: GPLv2+
  architecture: x86_64

# How to derive the value of the LABEL:version
version:
  mode: match
  repo: openshift-enterprise-docker

content:

  source:
    # If the source has an alias defined, an extracted local directory can be specified on the local file system
    # using --source alias path.
    alias: ose
    path: images/node
    dockerfile: Dockerfile
    recursive: true

    # Non-default modifications to perform on the git Dockerfile. Default steps include updating "FROM".
    modifications:
      - action: replace
        # Required field capturing why a particular change is necessary.
        description: Only origin requires this package. It is included in the RHEL package.
        match: "origin-sdn-ovs"
        replacement: ""
        # Should we fail if the replacement does not find a match? Defaults to false.
        optional: false