name: openshift3/oauth-proxy

from:
  stream: rhel

labels:
  vendor: Red Hat
  License: GPLv2+
  architecture: "x86_64"
  io.k8s.display-name: "OpenShift OAuth Proxy"
  io.k8s.description: "OpenShift OAuth Proxy."
  io.openshift.tags: "oauth"
