content:
  source:
    alias: jenkins
    path: '2'
    dockerfile: Dockerfile.rhel7
from:
  member: openshift-enterprise-docker
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Jenkins is a continuous integration server
  io.k8s.display-name: Jenkins 2.46
  io.openshift.tags: jenkins,jenkins2,ci
  vendor: Red Hat
name: openshift3/jenkins-2-rhel7
owners:
- bparees@redhat.com
repo:
  type: rpms
enabled_repos:
    - rhel-server-ose-rpms
