from:
  stream: rhel
labels:
  License: GPLv2+
  vendor: Red Hat
name: openshift3/apb-base
owners:
- Community
repo:
  type: rpms
enabled_repos:
    - rhel-server-ose-rpms
    - abp-rhel-server-extras-rpms
    - rhel-server-optional-rpms
