name: doozer-unit-tests

on:
  pull_request:
    paths:
      - 'doozer/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    container: fedora:38
    steps:
      - name: Install git
        run: dnf install -y git
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          set-safe-directory: ${{ env.GITHUB_WORKSPACE }}
      - name: Install packages
        run: dnf install -y gcc krb5-devel
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Create venv and install dependencies
        run: cd doozer && make venv
      - name: Run tests
        run: cd doozer && make test
